export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_STUDENT = 'ADD_STUDENT';
export const LOAD_STUDENT = 'LOAD_STUDENT';

export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';

